### PR TITLE
removed .DS_Store file from js/

### PR DESCRIPTION
**Pull request by Adjective-Object**
I am here to do housekeeping [ヽ(｡•́‿•̀)ﾉ](https://www.youtube.com/watch?v=YVEY24ieq08)

### CODE REVIEW

**Comment by arkon** [comment]
:shipit:

**Comment by elvinyung** [comment]
u w0t m8

**Comment by paulhroth** [comment]
+1

**Comment by RickEyre** [comment]
+1

**Comment by elliottsj** [comment]
+1

**Comment by jwebbed** [comment]
+1

**Comment by joeyrobert** [comment]
+1

**Comment by jwebbed** [comment]
+1

**Comment by Adjective-Object** [comment]
quality pull request here, I suggest we merge it right away.

**Comment by joeyrobert** [comment]
I agree.

**Comment by elvinyung** [comment]
10/10, great work guys

**Comment by RickEyre** [comment]
:whale:

**Pull request merged**
